### ISSUE TITLE
Missing environment in postman-file

### ISSUE THREAD

**Issue by BirgitSaalfeld** [ehrbase/fhir-bridge#113]
## Steps to reproduce ## 

In the current postman-file `fhir-bridge.postman_collection.json` the environment is missing. I set it manually with Severin as follows:
![image](https://user-images.githubusercontent.com/70131678/104449356-c6985d80-559e-11eb-9039-1837de02fee1.png)

## Actual result ##

No communication possible

## Expected result ##

Environment is part of postman-file

## Success criteria ##

- [ ] The defect has been fixed

**Comment by subigre** [comment]
I apologize, I had not noticed that environement are not exported together with the collection.
I think that it was the case in the past... maybe an update in the last versions of Postman.
In any case, I pushed the missing `fhir-bridge.postman_environment.json`.
