### ISSUE TITLE
Add support for 'Blood Gas Panel' profile

### ISSUE THREAD

**Issue by subigre** [ehrbase/fhir-bridge#142]
## Background ##

The FHIR-Bridge should support 'Blood Gas Panel' profile for the incoming Observation resource.

## Expected output ##

Add items here or describe what is expected as the result of the task, i.e. a wiki entry, a conceptual document or a configured tool that executes recurring tasks.

- [ ] Observation with 'Blood Gas Panel' profile are processed and validated
- [ ] An empty composition converter is registered for the mapping.

## Success criteria ##

- [ ] Output has been reviewed or presented and has been approved
- [ ] Documentation has been updated (Sphinx and Javadoc if applicable)

**Comment by SevKohler** [comment]
here is my [branch ](https://github.com/ehrbase/fhir-bridge/tree/feature/60_mapping_blood_gas) may safe you some time !
