### ISSUE TITLE
Error HTTP 422 when running createBloodPressure test

### ISSUE THREAD

**Issue by jsachau** [ehrbase/fhir-bridge#19]
The test runs fine on my local machine. However, when tested in circleci the test fails with the following exception:

```
[ERROR] createBloodPressure  Time elapsed: 0.522 s  <<< ERROR!
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Profile reference "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/blood-pressure" could not be resolved, so has not been checked
	at org.ehrbase.fhirbridge.FhirBridgeApplicationTestIT.createBloodPressure(FhirBridgeApplicationTestIT.java:231)
```

I have already replaced the .xml with the snapshot from simplifier.

The branch can be found [here](https://github.com/ehrbase/fhir-bridge/tree/feature/2_blood_pressure_mapping)
The circleci test results can be found [here](https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/27/workflows/b9e16944-34f2-4d6c-b343-83237aec896d/jobs/27/steps)
The pull request can be found [here](https://github.com/ehrbase/fhir-bridge/pull/15)

**Comment by wlad** [comment]
Please sync w/ develop branch after PR #18 was merged. Also be aware of the test file/class renaming so that your test does not get lost.

Increasing setSocketTimeout in the test (FhirBridgeApplicationTestIT.java on your branch) is what may help imediatly. It was at 60 previously.
```
@BeforeEach
        public void setUp() {
                context.getRestfulClientFactory().setSocketTimeout(30 * 1000);
                client = context.newRestfulGenericClient("http://localhost:" + port + "/fhir-bridge/fhir");

```

**Comment by ppazos** [comment]
@jsachau please check my response to this issue, I think it's the same: https://github.com/ehrbase/fhir-bridge/issues/16

**Comment by jsachau** [comment]
@wlad increasing the socket timeout fixed the error. Thanks!
