### ISSUE TITLE
Fix issue regarding output location for MappingOutput.json file

### ISSUE THREAD

**Issue by subigre** [ehrbase/fhir-bridge#205]
## Steps to reproduce ## 

Deploy de FHIR Bridge using Docker and send a request to create a FHIR resource.

## Actual result ##

NullPointerException and java.io.FileNotFoundException: src/main/resources/MappingOutput.json (No such file or directory)

## Expected result ##

The application should works and the file should be created in a configurable location.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by subigre** [comment]
Fixed #206

**Comment by SevKohler** [comment]
Please add Docuemntation to the wiki and an default output to the yml.

**Comment by subigre** [comment]
@SevKohler I apologize for the inconvenient made with this change and also because I forgot to inform you.

I have updated code in order to help @wlad that was blocked using the FHIR Bridge before my departure last Thuesday.
The use of the static path `src/main/resources/MappingOutput.json` prevented the Docker image published to start correctly.

I am not sure that we have to provide a default value for the output:
1. In my opinion, the feature should not be enabled by default as it is mainly used for development/debug.
2. It depends of the configuration and environement of each developer and I am not sure about Docker.

I will add the documentation as soon as I will come back.

**Comment by SevKohler** [comment]
1. i agree with debug being false, nevertheless adding an default path seems to be a good idea to me. 
I updated the wiki already and added a standard output path. Default for debug is still false. I hope this is okay for you.

**Comment by SevKohler** [comment]
i added a default path to the yml and updated the wiki.
