### ISSUE TITLE
FHIR bridge: problem with procedure profile

### ISSUE THREAD

**Issue by ppazos** [ehrbase/fhir-bridge#23]
BLOCKS: ehrbase/project_management#363 

Profile: https://simplifier.net/medizininformatikinitiative-modulprozeduren/prozedur

The exception:

`ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Unsupported fixed pattern type for discriminator(system) for slice Procedure.category.coding:sct: org.hl7.fhir.r5.model.UriType`

Note: it is strange it is complaining about a type defined in R5 (org.hl7.fhir.r5.model.UriType) if we are working with R4.

**Comment by subigre** [comment]
I fixed the issue and pushed the changes in the branch.

I updated the Prozedur profile and changed patternUri to fixedUri for:
- Procedure.category.coding:sct.system
- Procedure.code.coding:obs.system
- Procedure.code.coding:sct.system

HAPI FHIR only supports fixed value for primitive type.
_"Mostly used for fixing values of CodeableConcept. In general, pattern[x] is not intended for use with primitive types, where is has the same meaning as fixed[x]."_ (https://www.hl7.org/fhir/elementdefinition-definitions.html#ElementDefinition.pattern_x_)
