### ISSUE TITLE
SOFA Score Template "Unknown Template Error"

### ISSUE THREAD

**Issue by jsachau** [ehrbase/fhir-bridge#26]
## Steps to reproduce ## 

I have finished the mapping for the SOFA score (see [branch](https://github.com/ehrbase/fhir-bridge/tree/feature/42_mapping_sofa_score)). Afterwards I have added the .opt template file to my ehrbase endpoint. I double checked and retrieved the following template list (SOFA score was added successfully)

```
<?xml version='1.0' encoding='UTF-8'?>
<ArrayList>
    [...]
    <item>
        <concept>SOFA</concept>
        <template_id>SOFA</template_id>
        <archetype_id>openEHR-EHR-COMPOSITION.registereintrag.v1</archetype_id>
        <created_timestamp>2020-09-20T19:30:29.593Z</created_timestamp>
    </item>
</ArrayList>
```

## Actual result ##

When executing my test case I get the following error:

`ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : There was a problem saving the composition Unknown Template SOFA`

The same error occurs in the [circleci](https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/104/workflows/7f7953cc-5b22-44e9-bf4a-05944d6ff9e0/jobs/104) test. Note that I have added my template file to `OperationalTemplateData`.

## Success criteria ##

- [x] The defect has been fixed
- [x] The defect is checked by an unit or an integration test (Robot)
- [ ] Unit tests passed

**Comment by birgerhaarbrandt** [comment]
Hi @jsachau,

it looks like the template_ID provided at OperationalTemplateData is not the same that is used in the template. When I copied the one from within the template and added in the enum, it worked (at least I got a step further and ran into a different issue raised by the EHRbase backend).

hth

**Comment by birgerhaarbrandt** [comment]
I found the second error and now I get a passing unit test. Please change the DvOrdinals in the FhirObservationSofaScoreOpeneehrSofa.java using the following schema:

```
private static DvOrdinal ATEMFREQUENZ_SCORE_3 = new DvOrdinal(3L,
            new DvCodedText("3", new CodePhrase(new TerminologyId("local"), "at0018")));
```

Otherwise, Archie will automatically set the terminology ID to "UNKNOWN" instead of local which EHRbase will (correctly) reject.
