### ISSUE TITLE
Check the values of setSettingDefiningCode since everything is entered as secondary medical care

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/fhir-bridge#268]
@birgerhaarbrandt we need to check these values, since they do net seem appropiate

**Comment by ppazos** [comment]
@SevKohler in the FHIR profiles we generally don't receive information about the setting in which the care was given. I guess the value for this attribute could be set by some configuration, but we will not be sure unless we receive that info in the FHIR resource.
