### ISSUE TITLE
Unexpected 422 Errors in Condition examples

### ISSUE THREAD

**Issue by af-pwo** [ehrbase/fhir-bridge#288]
# Test Case/s To Reproduce Issue
Various Conditions

# path to test case
tests/robot/CONDITION/01_create.robot

# robot command to execute related test case(s) in your terminal/console
You have to be in this branch:
https://github.com/ehrbase/fhir-bridge/pull/283

robot -d results/ -L TRACE -i 288 robot

# by test case name

036 Create Chronic Kidney Disease (Disorder - Unknown)
040 Create Chronic Neurological or Mental Diseases (Combined disorder of muscle AND peripheral nerve)
041 Create Chronic Neurological or Mental Diseases (Dementia)
043 Create Chronic Neurological or Mental Diseases (Epilepsy)
048 Create Chronic Neurological or Mental Diseases (Multiple Sclerosis)
049 Create Chronic Neurological or Mental Diseases (Parkinson's Disease)
053 Create Cardiovascular Diseases (Carotid Artery Stenosis)
054 Create Cardiovascular Diseases (Coronary Arteriosclerosis)

## Actual Result

422 

## Expected Result

201

## Robot Error Message

{'issue': [{'code': 'processing',
                     'diagnostics': "unk-1: If verificationStatus is present, uncertaintyOfPresence-Extension SHALL NOT be present. [verificationStatus.exists() != Condition.modifierExtension.where(url = 'https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence').exists()]",
                     'location': ['Condition', 'Line 1, Col 2'],
                     'severity': 'error'},
                    {'code': 'processing',
                     'diagnostics': "The Extension 'https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence' must not be used as an extension (it's a modifierExtension)",
                     'location': ["Condition.extension[0][url='https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence']",
                                  'Line 1, Col 183'],
                     'severity': 'error'},
                    {'code': 'processing',
                     'diagnostics': 'Extension modifier mismatch: the extension element is not labelled as a modifier, but the underlying extension is',
                     'location': ["Condition.extension[0][url='https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence']",
                                  'Line 1, Col 183'],
                     'severity': 'error'}],

## Stacktrace

No Stacktrace logged

**Comment by SevKohler** [comment]
@wlad HAPI blocks this since not valid FHIR as it seems. 
@subigre can you verify that this is a invalid resource ?

**Comment by subigre** [comment]
@SevKohler, is this issue still valid?
I just saw that you already merged the branch with develop

**Comment by subigre** [comment]
@SevKohler, I checked all the input files used in the test cases mentioned above and the validation errors (HTTP 422) are "normal". 
* `create-cardiovascular-diseases-coronary-arteriosclerosis.json`
* `create-cardiovascular-diseases-carotid-artery-stenosis.json`
* `create-chronic-neurological-or-mental-disease-parkinsons.json`
* `create-chronic-neurological-or-mental-disease-multiple-sclerosis.json`
* `create-chronic-neurological-or-mental-disease-epilepsy.json`
* `create-chronic-neurological-or-mental-disease-dementia.json`
* `create-cardiovascular-diseases-coronary-arteriosclerosis.json`
* `create-chronic-kidney-disease-unknown.json`
* `create-chronic-neurological-or-mental-disease-muscle-and-peripheral-nerve.json`

The extension `https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence` is a modifier extension:

```xml
<element id="Extension">
    <path value="Extension" />
    <short value="Uncertainty of presence" />
    <definition value="Extension used on a condition resource if the presence of the condition is unknown." />
    <isModifier value="true" />
    <isModifierReason value="Modifies the meaning of the presence of a condition to being unknown." />
</element>
```
As a result the examples should contain the following: 
```json
 "modifierExtension": [
      {
        "url": "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence",
        "valueCodeableConcept": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "261665006",
              "display": "Unknown (qualifier value)"
            }
          ],
          "text": "Presence of condition is unknown."
        }
      }
    ],
```
instead of:
```json
 "extension": [
      {
        "url": "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence",
        "valueCodeableConcept": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "261665006",
              "display": "Unknown (qualifier value)"
            }
          ],
          "text": "Presence of condition is unknown."
        }
      }
    ],
```
