### ISSUE TITLE
Questionnaire - Code above-42C is not accepted

### ISSUE THREAD

**Issue by fkaercher** [ehrbase/fhir-bridge#289]
## Steps to reproduce ## 

Question: "Wie hoch war die höchste Temperatur ca.?"   Selected answer: "Über 42°C"

## Actual result ##

Error: ""fewer max temperature: above-42C is not a valid code value !"

## Expected result ##

The code "above-42C" should be accepted.

## Success criteria ##

- [x ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
fixed
