### ISSUE TITLE
Questionnaire - fewer max temperature: LA32-8 is not accepted

### ISSUE THREAD

**Issue by fkaercher** [ehrbase/fhir-bridge#290]
## Steps to reproduce ## 

Question: "Wie hoch war die höchste Temperatur ca.?" Selected answer: "Ich weiß es nicht"

## Actual result ##

Error: "fewer max temperature: LA32-8 is not a valid code value !"

## Expected result ##

The code "LA32-8" should be accepted.

## Success criteria ##

- [x ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
@SevKohler add also mapping test for this cases

**Comment by SevKohler** [comment]
@fkaercher thats the wrong coding in the fewer class the code LA12688-0 is used for ich weiss es nicht see:
https://simplifier.net/data4lifefhirartifactsr4/fever-class-vs-de
So the message is correct
