### ISSUE TITLE
rename package org.ehrbase.fhirbridge.ehr.converter.specific.virologischerBefund to "geccovirologischerbefund"

### ISSUE THREAD

**Issue by ZhuYufei990** [ehrbase/fhir-bridge#334]
## Steps to reproduce ## 

package org.ehrbase.fhirbridge.ehr.converter.specific.virologischerBefund now in the project is actually for GECCO virologischer Befund, Mapping for the template with name "virologischer Befund" by SmICS is in progress.

## Actual result ##

conflict with package name

## Expected result ##

packages with full name bring no conflict.

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
Can you also rename DnrAnordnung package  to dnranordnung  when you do this, thanks.
https://github.com/ehrbase/fhir-bridge/tree/develop/src/main/java/org/ehrbase/fhirbridge/ehr/converter/specific/DnrAnordnung

**Comment by ZhuYufei990** [comment]
I've just renamed the both packages.
