### ISSUE TITLE
BloodGasPanel upload ArrayList cannot be cast to class RMObject

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/fhir-bridge#34]
## Steps to reproduce ## 

Pull branch feature_60 and upload the attached json to the url: (POST) http://localhost:8888/fhir-bridge/fhir/Bundle
Error occurs in line 44 of LaborergebnisBefundMapper, when mapping any of the Clusters and setting it for the LaborergebnisBefundMapper (this does not only count for setKohlendioxidpartialdruck, but also for any following setter for Clusters (currently they are commented)). They can be empty or use the mapping, error is the same.  When commenting these setters, the error disappears and the Bundle is successfully uploaded. 

## Actual result ##

"Failed to call access method: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class com.nedap.archie.rm.RMObject (java.util.ArrayList is in module java.base of loader 'bootstrap'; com.nedap.archie.rm.RMObject is in unnamed module of loader 'app')"

## Expected result ##
Uploading the Bundle successfully

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by stefanspiska** [comment]
Duplikate of  https://github.com/ehrbase/fhir-bridge/issues/35
