### ISSUE TITLE
Test failures and errors in fhir bridge

### ISSUE THREAD

**Issue by NormanWeinert** [ehrbase/fhir-bridge#341]
## Steps to reproduce ## 

Run fhir bridge with  "mvn clean verify -DskipITs=false"

## Actual result ##

4 test failures and 1 test error encountered:

[ERROR] Failures:
[ERROR]   DiagnosticReportIT.createWithInvalidCode:49 expected: <HTTP 422 : This element does not match any known slice defined in the profile https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab> but was: <HTTP 422 : Dieses Element stimmt mit keinem bekannten Slice defined in the profile https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/DiagnosticReportLab überein.>
[ERROR]   ObservationIT.createWithInvalidQuantityDatatype:126 expected: <HTTP 422 : Error parsing JSON: the primitive value must be a number> but was: <HTTP 422 : Fehler beim Parsen von JSON: Der primitive Wert muss eine Zahl sein.>
[ERROR]   PatientIT.createInvalid:55 expected: <HTTP 422 : Extension.extension:dateTimeOfDocumentation: minimum required = 1, but only found 0 (from https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/age)> but was: <HTTP 422 : Extension.extension:dateTimeOfDocumentation: mindestens erforderlich = 1, aber nur gefunden 0>
[ERROR]   QuestionnaireResponseIT.createInvalid:76 expected: <HTTP 422 : QuestionnaireResponse.status: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse)> but was: <HTTP 422 : QuestionnaireResponse.status: mindestens erforderlich = 1, aber nur gefunden 0>
[ERROR] Errors:
[ERROR]   FindProcedureTransactionIT.findProcedureSearch:48->AbstractTransactionIT.search:55 » InternalError
[INFO]
[ERROR] Tests run: 254, Failures: 4, Errors: 1, Skipped: 11

## Expected result ##

All tests pass with no failures or errors.

**Comment by subigre** [comment]
@NormanWeinert, could you please tell me on which branch you are experiencing the issue?

I just tried on develop I do not have fail or error:
```
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 250, Failures: 0, Errors: 0, Skipped: 11
[INFO] 
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.5.0:stop (post-integration-test) @ fhir-bridge ---
[INFO] Stopping application...
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ fhir-bridge ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:report (default-report) @ fhir-bridge ---
[INFO] Loading execution data file D:\Projets\fhir-bridge\target\jacoco.exec
[INFO] Analyzed bundle 'FHIR Bridge' with 809 classes
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ fhir-bridge ---
[INFO] Installing D:\Projets\fhir-bridge\target\fhir-bridge-1.2.0-SNAPSHOT.jar to C:\Users\subigre\.m2\repository\org\ehrbase\fhirbridge\fhir-bridge\1.2.0-SNAPSHOT\fhir-bridge-1.2.0-SNAPSHOT.jar
[INFO] Installing D:\Projets\fhir-bridge\pom.xml to C:\Users\subigre\.m2\repository\org\ehrbase\fhirbridge\fhir-bridge\1.2.0-SNAPSHOT\fhir-bridge-1.2.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:45 min
[INFO] Finished at: 2021-06-04T14:25:30+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by NormanWeinert** [comment]
@subigre Auf "feature/NUM-128_Virologischer-Befund" an dem ich gerade am arbeiten bin - ist schon etwas weiter als der jetzige comittete branch hierzu. 
Ich habe nichts an den oben vorkommenden Testklassen geändert, deswegen dachte ich es müsste schon in develop auftauchen.

**Comment by subigre** [comment]
I just noticed two things from your output:

1. You have 4 more tests than the current develop branch
2. The errors look stranges because the expected results are OK.
   However, the error messages are translated in German in your case:

```
expected: <HTTP 422 : QuestionnaireResponse.status: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/QuestionnaireResponse)>

but was: <HTTP 422 : QuestionnaireResponse.status: mindestens erforderlich = 1, aber nur gefunden 0>
```

**Comment by NormanWeinert** [comment]
"1. You have 4 more tests than the current develop branch"

Yes, these are new tests for my conversion template that I am currently working on. They are not yet comitted.

"2. The errors look stranges because the expected results are OK.
However, the error messages are translated in German in your case: "

I don't know why this happens to be honest. I did not change any language setting for this test.

**Comment by SevKohler** [comment]
Logically these messages are right (just in the wrong languages), therefore the tests are correct.  My developlment enviornment is also german therefore i often have the same failures, i just ignore those (since they are no failures), sonarcloud varifies their correctness in addition to that.

**Comment by NormanWeinert** [comment]
Thank you for the information. I was not aware of that. Ok, then these can be ignored. I closed the issue now.

**Comment by subigre** [comment]
@SevKohler, do you also have the issue?
I do not understand why it happens only with German and not in my case with French.
Or may be there is no error messages translated in French so I always receive the default English ones. 
But just to be sure, I will have a look from where those messages comes from (HAPI FHIR or the `StructureDetfinition`) to check if it is only related to message translations.

**Comment by SevKohler** [comment]
I dont have a clue to be honest, my enviornment is actually english and so is my JDK. Would welcome if you take a look. Better would be if we could somehow define more specific types instead of comparing Exception strings. Anyhow i think this cost too much time, since priorities are else where for now. Would be nice if you could take a look.
