### ISSUE TITLE
In branch "feature/NUM-128_Virologischer-Befund" the attribute "Ergebnis-Status" of the composition "Virologischer Befund" is not saved in the ehrbase server.

### ISSUE THREAD

**Issue by NormanWeinert** [ehrbase/fhir-bridge#344]
## Steps to reproduce ## 

1.) Start fhir-bridge and ehrbase.
2.) Create Virologischer Befund with "src/test/resources/Bundle/VirologischerBefund/create-virologischer-befund.json"
3.) After the creation with result "200 OK" go to the swagger UI of ehrbase and find the just created composition. The result should be: "src/test/resources/Bundle/VirologischerBefund/paragon-create-virologischer-befund.json".
4.) "Ergebnis-Status" in "Pro Analyt Cluster" of "Labortest-Panel" does not exist in the created composition. 

## Expected result ##

"Ergebnis-Status" is set properly depending on the value of "observation.status".  
"Ergebnis-Status" should be "Endbefund" as "observation.status" was set to "final". 

The OPEN Ehr values of the complete composition can be seen here: http://88.198.146.13/ckm/templates/1246.169.636

Resulting paragon mapping test differences:

NewObject{ new object: org.ehrbase.fhirbridge.ehr.opt.virologischerbefundcomposition.VirologischerBefundComposition/#befund/jedesEreignis/0/labortestPanel/proAnalyt/0/ergebnisStatus/0 }
NewObject{ new object: org.ehrbase.fhirbridge.ehr.opt.virologischerbefundcomposition.VirologischerBefundComposition/#befund/jedesEreignis/0/labortestPanel/proAnalyt/0/ergebnisStatus/0/value2/0 }
ListChange{ 'befund/jedesEreignis/0/labortestPanel/proAnalyt/0.ergebnisStatus' collection changes :
  0. 'org.ehrbase.fhirbridge.ehr.opt.virologischerbefundcomposition.VirologischerBefundComposition/#befund/jedesEreignis/0/labortestPanel/proAnalyt/0/ergebnisStatus/0' added }

Ehrbase status:

{
  "ehrbase_version": "0.16.5",
  "openehr_sdk_version": "39cb1fd",
  "archie_version": "5a4a9442e5e2516aed5f25636ac236682aace7b9",
  "jvm_version": "AdoptOpenJDK 11.0.11+9",
  "os_version": "Windows 10 amd64 10.0",
  "postgres_version": "PostgreSQL 13.2, compiled by Visual C++ build 1914, 64-bit"
}

**Comment by SevKohler** [comment]
@ErikTute this was you mapping, can you check ?

**Comment by SevKohler** [comment]
@ErikTute did already a virologischer befgund mapping initially.
 @NormanWeinert hjow does this mapping differ ?
 Sry i have problems following up after being sick .
 
 Did you check the mapping output before it was send to ehrbase ? 
 Did it contain the fields that are afterwards missing ? 
 If yes you need to put the issue to the ehrbase team. 
 If not then there is a error in the mapping. 
 
 You can find the mapping output at:  ${java.io.tmpdir}/mappings, before it gets send to ehrbase.

**Comment by NormanWeinert** [comment]
@SevKohler 
At {java.io.tmpdir}/mappings the Ergebnis-Status field is also missing. 

So there should be an error in the mapping.
