### ISSUE TITLE
Create documentation of the new camel flows

### ISSUE THREAD

**Issue by ppazos** [ehrbase/fhir-bridge#37]
Would be useful to have some kind of diagram explaining what happens inside the camel steps.

This is specified in the 'routes' classes.

**Comment by SevKohler** [comment]
first draft is done, i sent an mail to @subigre and asked him to check the content (take a look in the wiki of the project). @ppazos would you like a flow chart for every specific route (resource type) ? I did already [one](https://drive.google.com/file/d/14blDTU7aB0mMUKBHdYvAubnWT13rOyO_/view)(needs update and alteration so its more generic for observation)  did you meant smt like that ?

**Comment by SevKohler** [comment]
Flows are documented in the wiki
