### ISSUE TITLE
Add support for OpenAPI Specification/Swagger UI

### ISSUE THREAD

**Issue by subigre** [ehrbase/fhir-bridge#37]
## Background ##

Add support for OpenAPI Specification/Swagger UI in FHIR-Bridge application

## Expected output ##

OpenAPI specification should be generated based on the `@RestController` classes and accessible using Swagger UI.

- [ ] OpenAPI specification is generated from the source code.
- [ ] Swagger UI displays the documentation and allows 

## Success criteria ##

- [ ] All REST services implemented are described/documented.

**Comment by birgerhaarbrandt** [comment]
Result: this is not possible.
