### ISSUE TITLE
Unexpected Parsing Error for Condition Example Symptom Absent/Present

### ISSUE THREAD

**Issue by jsachau** [ehrbase/fhir-bridge#41]
## Steps to reproduce ## 

I have included proper examples for symptoms absent and symptoms present in my branch [61_mapping_symptoms](https://github.com/ehrbase/fhir-bridge/tree/feature/61_mapping_symptoms). When executing my test `createSymptom` I get the following parsing error:

```
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Internal error: Problem with use of resolve() - profile [CanonicalType[https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/certainty-of-absence]] on Condition.extension:certaintyOfAbsence could not be resolved
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Internal error: Problem with use of resolve() - profile [CanonicalType[https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/certainty-of-presence]] on Condition.extension:certaintyOfPresence could not be resolved
```

## Success criteria ##

- [ ] The defect has been fixed
- [ ] Unit tests passed

**Comment by ppazos** [comment]
@jsachau I think the issue might be the extension in not defined in the profile but I'm not sure, need to consult @subigre

**Comment by subigre** [comment]
Your are right @ppazos, the FHIR Bridge does not know `https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/certainty-of-presence`. I encountered a similar issue with `MII-Reference` in the past.
@jsachau, you just have to register this additional profile in the application in order to fix the issue.

**Comment by jsachau** [comment]
Registering the additional profile did fix the issue.
