### ISSUE TITLE
Refactor MII Prozedure

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/fhir-bridge#415]
@NormanWeinert can you maybe help us here and refactor that [one](https://github.com/ehrbase/fhir-bridge/tree/develop/src/main/java/org/ehrbase/fhirbridge/ehr/converter/specific/procedure), since its part of the MII mappings and important for you guys too, i guess ?
You already know what to do and what things are important now after (pretty sure soon done) viro befund.
If you guys dont need it i would suggest we even delete it or mark it as deprecated ?

**Comment by NormanWeinert** [comment]
I do not know if MII Prozedure is needed. I will gain intel on that first.
