### ISSUE TITLE
Docker quick start not completing  image download.

### ISSUE THREAD

**Issue by CzarMich** [ehrbase/fhir-bridge#483]
##Error:
Pulling logstash (logstash:7.7.0)...
7.7.0: Pulling from library/logstash
524b0c1e57f8: Already exists
676f059574bb: Pull complete
e974e49ddee7: Pull complete
3423b075bb4a: Pull complete
e01d6bcefef9: Pull complete
5859d91fec22: Pull complete
ab4d03277214: Pull complete
4f51455693d8: Pull complete
8474cc37cb13: Pull complete
d98f382646ef: Pull complete
0ac989b6ae1c: Pull complete
Digest: sha256:8a3665c521e7b6b1517bb1fad320e2db87f93e2c6f098dd04c7e119a3c0d2017
Status: Downloaded newer image for logstash:7.7.0
Pulling fhir-bridge (ehrbase/fhir-bridge:latest)...
ERROR: manifest for ehrbase/fhir-bridge:latest not found: manifest unknown: manifest unknown

**Comment by paulolaup** [comment]
If I recall correctly u have to change the entry in the YML-File. You need :next instead of :latest. I was able to fix the issue that way.

**Comment by CzarMich** [comment]
> If I recall correctly u have to change the entry in the YML-File. You need :next instead of :latest. I was able to fix the issue that way.

Great. worked. 
Thanks
