### ISSUE TITLE
src/test/resources/Insomnia_2020-07-27.json does not exist

### ISSUE THREAD

**Issue by fergusleen** [ehrbase/fhir-bridge#529]
## Steps to reproduce ## 

Following instructions to run Insomnia tests I get a 404 for https://github.com/ehrbase/fhir-bridge/blob/develop/src/test/resources/Insomnia_2020-07-27.json and it does not exist under src/test/resources

## Actual result ##

404

## Expected result ##

Insomnia_2020-07-27.json

## Success criteria ##

- [ ] The defect has been fixed

**Comment by fergusleen** [comment]
I have found the manual-tests using VSCode. It may be a case of documentation needing updating?

**Comment by SevKohler** [comment]
Yeah unfortunatly we are all super busy currently :(
We use the postman API (example  requests are in https://github.com/ehrbase/fhir-bridge/tree/develop/config/postman ), insomnia is deprecated for this project.
Unfortunatly also some of the postman requests are deprecated, anyhow the unit tests use up to date files you can use them for testing.
