### ISSUE TITLE
Creating Patient with least amount of identifying data. (Privacy in mind)

### ISSUE THREAD

**Issue by CzarMich** [ehrbase/fhir-bridge#534]
So, since we are working with research data of actual patients. we leave out some patient identifying information and store only a few that we need. 

Could it possible that  we can create a patient with the least amount of data. E.g Creating a patient with only source system identifier.  Or source system ID and only Date of Birth.

Thanks.

Michael.

**Comment by SevKohler** [comment]
Sure one can always enter nothing if required afaik. 
Did you already tried it.

**Comment by CzarMich** [comment]
Closed with #533
