### ISSUE TITLE
Coding.display Should Be Optional Even if No Terminology-Service Is Configured

### ISSUE THREAD

**Issue by hhund** [ehrbase/fhir-bridge#563]
If no terminology-service is configured, Coding.display is currently mandatory.

https://github.com/ehrbase/fhir-bridge/blob/8a83d4b2860a7fc080970bdb8c7ed99e569e4c26/src/main/java/org/ehrbase/fhirbridge/ehr/converter/DvCodedTextParser.java#L57-L58

See also: https://github.com/ehrbase/fhir-bridge/blob/develop/src/test/java/org/ehrbase/fhirbridge/ehr/converter/DvCodedTextParserTest.java#L24-L31

Due to the fragility of the HAPI FHIR based validation mechanism, a terminology-server is typically not configured for the FHIR Bridge and validation of codes is only performed by EHRBase.

Since Coding.display is not mandatory in NUM-CODEX FHIR profiles and generally not mandatory in the [FHIR R4 specification (cardinality 0..1)](http://hl7.org/fhir/R4/datatypes.html#Coding). Valid FHIR resources are currently rejected by the FHIR Bridge.

**Comment by birgerhaarbrandt** [comment]
Hi @hhund,

the main issue is that openEHR requires the equivalent of a display code to provided mandatorily.  We can think about putting in some dummy values for the time being. I think there is also a case to the relax these constraints inside the openEHR RM, but this might take a time to get this part of the next release (if everyone agrees that this is a good idea). We can check some options internally.

**Comment by hhund** [comment]
Ah, good to know. Relaxing the Rules of the FHIR Bridge and than fixing missing `display` values within EHRBase should work.
As a last resort (if both services don't have a terminology server configured) I would use the value from `code` for `display`.
