### ISSUE TITLE
No converter available for Observation pH

### ISSUE THREAD

**Issue by hhund** [ehrbase/fhir-bridge#578]
## Steps to reproduce ## 
Create / Update Ressource with Profile `https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/pH`

## Actual result ##
```
2022-06-25 19:38:53.871 ERROR 1 --- [nio-8888-exec-9] o.a.c.p.e.DefaultErrorHandler            : Failed delivery for (MessageId: 0B173FACC33C882-0000000000000007 on ExchangeId: 0B173FACC33C882-0000000000000007). Exhausted after delivery attempt: 1 caught: ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: No converter available for Observation with profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/pH
```
HTTP 422

## Expected result ##

HTTP 200 / 201

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by hhund** [comment]
Please double check converter availability for the following NUM-CODEX profiles:
```
https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/blood-gas-panel

https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/carbon-dioxide-partial-pressure
https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/oxygen-partial-pressure
https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/oxygen-saturation
https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/inhaled-oxygen-concentration
```

**Comment by SevKohler** [comment]
@birgerhaarbrandt is this a mapping we want to support as single resource or just as part of the bloodgas Bundle.
As of now this is only supported as part of the Bloodgaspanel bundle.

**Comment by SevKohler** [comment]
@hhund Ph is not meant to be send as a single ressource and has to be provided as part of the Bloodgas bundle. 
AFAIK this was communicated a year ago, otherwise write @birgerhaarbrandt a mail.
