### ISSUE TITLE
Circle CI Build Failing After Illegal Reflective Access Operation

### ISSUE THREAD

**Issue by jsachau** [ehrbase/fhir-bridge#58]
In my current [branch](https://github.com/ehrbase/fhir-bridge/tree/feature/72_mapping_patient_in_icu), the CircleCI tests were failing (see [link](https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/244/workflows/e3215b64-e910-4eea-9d88-9596934fdc16/jobs/264)), because it could not start the FHIR-Bridge application. After reviewing the error I found that "Start EHRBASE Server" and "Start FHIRBRIDGE Application" output the following warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
FHIRBRIDGE_VERSION: 1.0.0-SNAPSHOT
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils (file:/home/circleci/projects/target/lib/spring-core-5.2.9.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by wlad** [comment]
Hi @jsachau thanks for reporting. This warning messages is a known issue which was not adressed yet but they don't cause the fail. 
It seems that with one of the last commits the way how fhirbridge picks up it's configuration has changed - this breaks the CI and I can also reproduce it locally. I will open a separate issue for that.
