### ISSUE TITLE
Fhir Profile Validation Fails

### ISSUE THREAD

**Issue by jsachau** [ehrbase/fhir-bridge#81]
For the diagnosis mapping, I have added multiple profiles to fhir-bridge. A diagnosis can be absent, present or unknown. For the present and absent case, the condition has to include a validation status. For the unknown case, the condition has to include an "uncertainty-of-presence" extension. In the later case, the validation fails with the following error:

```
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : unk-1: If verificationStatus is present, uncertaintyOfPresence-Extension SHALL NOT be present. [verificationStatus.exists() != Condition.extension.where(url = 'https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence').exists()]
	at org.ehrbase.fhirbridge.fhir.ConditionIT.create(ConditionIT.java:226)
	at org.ehrbase.fhirbridge.fhir.ConditionIT.createDiagnoseRheumatologicalImmunologicalDiseases(ConditionIT.java:97)
```

After investigating my example, I found that the `verficationStatus` is not present and the validation seems to have an error. Here is the full example:
```
{
  "resourceType": "Condition",
  "id": "e28106c0-6b03-4ef2-9f99-50c9f9309166",
  "meta": {
    "profile": [
      "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/rheumatological-immunological-diseases"
    ]
  },
  "modifierExtension": [
    {
      "url": "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "http://snomed.info/sct",
            "code": "261665006",
            "display": "Unknown (qualifier value)"
          }
        ],
        "text": "Presence of condition is unknown."
      }
    }
  ],
  "category": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "394810000",
          "display": "Rheumatology"
        },
        {
          "system": "http://snomed.info/sct",
          "code": "408480009",
          "display": "Clinical immunology"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "69896004",
        "display": "Rheumatoid arthritis"
      }
    ]
  },
  "subject": {
    "identifier": {
      "system": "urn:ietf:rfc:4122",
      "value": "{{patientId}}"
    }
  },
  "recordedDate": "2020-10-06"
}
```

The source code can be found [here](https://github.com/ehrbase/fhir-bridge/tree/feature/104_diagnose_mapping). The error is not restricted to this profile and occurs in most of the other cases, too (see [here](https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/237/workflows/c88490da-1016-4604-bc2f-06d1dd87afc1/jobs/435/tests)).

**Comment by ppazos** [comment]
@jsachau the rule seems to look for 'extension'

`... Condition.extension.where ...`

And the resource has 'modifierExtension'.

Not sure if that is the issue, but might be related.

So this:

`verificationStatus.exists() != Condition.extension.where(...).exists()`

Might really evaluate to:

`false != false`

**Comment by jsachau** [comment]
As in the symptoms profile I had to manually change the name `extension` to `modifierExtension` in the example, because the validation threw an error. So someone has to fix the profile and change the extension to a modifierExtension for all validations?

**Comment by ppazos** [comment]
@subigre can you comment on this one?

**Comment by jsachau** [comment]
I wrote Julian Saß and told him about the problem. I will paste his response once he reaches out to me.

**Comment by subigre** [comment]
No need to comment... you are absolutely right @ppazos 👍 

The extension `https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence` is a specific extension => [Modifier Extension](https://www.hl7.org/fhir/extensibility.html#modifierExtension)
This modifier extension requires to use `modifierExtension` instead of `extension` in the FHIR resource.

As you already mentioned the constraint is incorrect (checking `Condition.extension.where`) and this profile should be updated in order to fix the issue.

**Comment by ppazos** [comment]
@subigre you rock, thanks!

**Comment by ppazos** [comment]
@jsachau did you get feedback on this issue?

**Comment by jsachau** [comment]
@ppazos: Yes @subigre was right and the profiles had to be updated. Julian Saß has fixed the error.

Thanks!

**Comment by ppazos** [comment]
@jsachau can we close this issue?
