### ISSUE TITLE
Parsing error with extension

### ISSUE THREAD

**Issue by jsachau** [ehrbase/fhir-bridge#99]
I'm currently having an issue while parsing a specific example of the [Symptom](https://simplifier.net/ForschungsnetzCovid-19/SymptomsCovid19-profile/~json) profile. My example contains the  following extension
```
 "extension":  [
        {
            "url": "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence",
            "valueCodeableConcept": {
                "coding":  [
                    {
                        "code": "261665006",
                        "display": "Unknown (qualifier value)",
                        "system": "http://snomed.info/sct"
                    }
                ],
                "text": "Presence of symptom is unknown."
            }
        }
    ]
```

I have added the profile for `https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence` to the profiles directory. However, when parsing the [example](https://simplifier.net/ForschungsnetzCovid-19/Condition-example-duplicate-78/~json) I get the following exception:

```
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Die Extension "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence" darf nicht als Extension verwendet werden (es handelt sich um eine ModifierExtension)
```

I have already spoken to the person who created the profile and the extension should be allowed and is also recognized by the Simplifier validator. I assume that there is an issue in the parsing component.

**Comment by ppazos** [comment]
@jsachau I don't know how extensions should be loaded, it might be a similar case to the MII-Reference we had some time ago. @subigre do you know how an extension should be configured?

**Comment by subigre** [comment]
@jsachau @ppazos I apologize for the late reply.

Exentions and profiles are using the same mechanism (https://www.hl7.org/fhir/profiling.html) and the corresponding `StructureDefinition` must be included in application.

**Comment by ppazos** [comment]
thanks @subigre besides adding the profile like @jsachau did, does she need to do anything else?

it would be great if you can take a look at her branch https://github.com/ehrbase/fhir-bridge/tree/feature/61_mapping_symptoms

**Comment by jsachau** [comment]
@subigre was right, adding the StructureDefinition is enough. It seems like I had an issue where the profiles .xml files were not updated in the final build. After restarting my computer, the error disappeared.

**Comment by subigre** [comment]
I had this issue from time to time and it appears when I build the project directly in intellij. Now, I am always using` mvn clean package` whenever I add a new profile.

**Comment by jsachau** [comment]
I have finished my mapping and wanted to create a pull request when I notices that the error still occurs in the [circle ci build](https://app.circleci.com/pipelines/github/ehrbase/fhir-bridge/472/workflows/1c5781d1-f947-4d1a-bb3f-737f0a6dd37b/jobs/740/tests):

```
ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 : Unknown extension https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/uncertainty-of-presence
	at org.ehrbase.fhirbridge.FhirBridgeApplicationIT.createSymptom(FhirBridgeApplicationIT.java:572)
```

@subigre How did you force a clean build there?
